### ISSUE TITLE
In page navigation too far

### ISSUE THREAD

**Issue by Levino** [hardforkio/homepage#130]
When I click on "mehr" in the hero section I am scrolled down to the "offerings" section. But the navbar overlaps the content. We need to somehow get in some offset to take care of the navbar.

**Comment by Levino** [comment]
Give this [solution](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header) a spin.

**Comment by EmCeeEs** [comment]
Used this solution: https://css-tricks.com/hash-tag-links-padding/

**Comment by Levino** [comment]
Fixed by #165
