### ISSUE TITLE
Display a useful preview when editing data in the CMS UI

### ISSUE THREAD

**Issue by Bakkhos** [hardforkio/homepage#134]
Currently Netlify CMS' WYSIWYG visual preview is not configured. 

Set this up so that for certain collections, such as Imprint or Jobs, we can see a preview of parts of the website where that data is used (e.g. Invidual Job page when editing a Job)

I have a minimal impementation in https://github.com/hardforkio/homepage/commit/48cccc8d1b2eff13a4c85f5ccde24e432b8a98cb  but it's not really production quality (e.g. stylesheets are still not integrated)

**Comment by kiliw** [comment]
#180 adds the stylesheets to the preview in netlify cms. Now only the preview templates have to use the display components similar to the storybook

**Comment by Levino** [comment]
See https://github.com/hardforkio/homepage/issues/217

**Comment by Levino** [comment]
Kind of solved.
