### ISSUE TITLE
Enable i18n

### ISSUE THREAD

**Issue by Levino** [hardforkio/homepage#141]
We want i18n. We will start with the imprint. The current German imprint should be accessible under `/de/imprint/` and the link to the imprint on the page should be updated accordingly. On top add a route `/en/imprint` that renders the English version of the imprint page. Do not add a link to this english translation (we will add a language switch later).

**Comment by Bakkhos** [comment]
As described the issue is done; to work on the broader goal of pervasive internationalization I think the next logical step is to move more data into the CMS, and to create internationalized versions while doing so

**Comment by Bakkhos** [comment]
The issue needs an update. Should we add /en/X and de/X routes for internationalized versions of all existing routes?
