### ISSUE TITLE
Run test in CI to see that typescript is correct

### ISSUE THREAD

**Issue by Bakkhos** [hardforkio/homepage#201]
Gatsby does [only transpile](https://www.gatsbyjs.org/packages/gatsby-plugin-typescript/#caveats) the typescript code. We need to add a "compile" check in CI running `yarn tsc --noEmit`.

**Comment by Levino** [comment]
Gatsby does [only transpile](https://www.gatsbyjs.org/packages/gatsby-plugin-typescript/#caveats) the typescript code. We need to add a "compile" check in CI running `yarn tsc --noEmit`.
