### ISSUE TITLE
German text on english home page

### ISSUE THREAD

**Issue by Levino** [hardforkio/homepage#229]
On the English home page:
![Selection_276](https://user-images.githubusercontent.com/1150767/69046168-a7cd2400-09f8-11ea-87df-9ac97f421f9e.jpg)
![Selection_277](https://user-images.githubusercontent.com/1150767/69046116-866c3800-09f8-11ea-8d32-c91e65ebb17a.jpg)
All these values should be in the CMS and translated.

**Comment by kiliw** [comment]
![Selection_149](https://user-images.githubusercontent.com/43745180/69407847-ccc9db80-0d05-11ea-95b8-4ba8c80dee7f.png)

On the english page we still have the german text

**Comment by Bakkhos** [comment]
There is one other such problem: The imprint link in the footer always links to /de/imprint (even on the english page)

**Comment by Bakkhos** [comment]
And the FAQ link in the navbar always goes to /de/faq
