### ISSUE TITLE
Build localized string widget for netlify CMS.

### ISSUE THREAD

**Issue by EmCeeEs** [hardforkio/homepage#281]
The current experience of using netlify CMS' editor is poor: Nesting is too deep and it is hard to keep track of page translations.

**ToDo**
Build a custom widget that supports multiple localized strings for each field.

**QA**
- Open build preview, go to `/admin` and click on footer entry.
- Verify that ImprintLinkText has localized input for english and german
- Verifiy that content is queried correctly for english and german preview
- Minimum 1 translation is needed in order to save

**Comment by EmCeeEs** [comment]
**Links**
https://www.netlifycms.org/docs/custom-widgets/#docs-content

**Comment by Bakkhos** [comment]
This would be super nice to have!
