### ISSUE TITLE
Redirect non-german users to /en

### ISSUE THREAD

**Issue by Levino** [hardforkio/homepage#350]
Currently we forward all users to /de. This was because we did not have a full English translation of the homepage.
https://github.com/hardforkio/homepage/blob/65fc9ad9ab818f964a66957c4241d8ec9f4ebea8/static/_redirects#L1-L2

Now as we have all content in English we should forward only users from Germany (speaking countries) to /de. The rest should go to /en.

**Comment by EmCeeEs** [comment]
https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/

**Comment by EmCeeEs** [comment]
https://docs.netlify.com/routing/redirects/redirect-options/#redirect-by-country-or-language
