### ISSUE TITLE
Other websites cannot link to sections on the homepage using a #hash in the URL

### ISSUE THREAD

**Issue by Bakkhos** [hardforkio/homepage#378]
A link with a hash id, such as https://hardfork.io/de/software#screenshots, should make the viewport open with the relevant DOM element at the top of the viewport. Instead it opens the page the same way as https://hardfork.io/de/software does.

Only if you navigate to the URL twice, does the screen scroll down:
![demo](https://user-images.githubusercontent.com/93765/77883909-52d1d200-7264-11ea-9295-28d3c6b22a2a.gif)

**Comment by Levino** [comment]
Gatsby and anchor tags are a pain...

**Comment by Levino** [comment]
Actually we have code that should have fixed this:
https://github.com/hardforkio/homepage/blob/20bbfaf25d5b0a544746cf9f8acc6896ad2b3ba3/gatsby-browser.js#L10-L16

Somehow it stopped working...

**Comment by Levino** [comment]
Now it works for me. Can you confirm @Bakkhos ? If not try to delete all site data and kill all chrome instances and try again. It is a very funky bug.

**Comment by Levino** [comment]
I think I fixed it by removing the service worker resp. the `gatsby-plugin-offline`. Please try again and reopen if it still is an issue for you @Bakkhos
