### ISSUE TITLE
Code examples are not easy to find.

### ISSUE THREAD

**Issue by jakobkolb** [hardforkio/homepage#404]
#### What I see:

The page advertises how much the company values transparency and accountability for their work. However, the link to their GitHub where one could check this out is very small and hidden in the footer on the page.

#### What I expect to see:

A Prominent link to the company GitHub and/or specific code examples in the context where it is relevant. 

#### Suggestions

-  Use a [fork me on github banner](https://github.blog/2008-12-19-github-ribbons/) to quickly guide users to our github repo.
- Place a link to our github organization in the "Quality and Transparency" section

**Comment by Levino** [comment]
Superseded by #415
