### ISSUE TITLE
Internationalization of Software subpage

### ISSUE THREAD

**Issue by jakobkolb** [hardforkio/homepage#407]
**Current behavior**:

With the language set to English, navigating to the software page lands me on a German page and also sets the language to German such that when I continue navigating the page, the language stays set to German.

**Expected behavior**:

Even when navigating to the software subpage one wants to stick with the language (in this case English)

**Comment by Levino** [comment]
Remark: Just copy and paste all the German content as the "English" version and stop the "special treatment".
