### ISSUE TITLE
Add a Cookie notice

### ISSUE THREAD

**Issue by jakobkolb** [hardforkio/homepage#410]
#### What I see:

There is no notice about the usage of cookies what I land on the page

#### What I expect:

Some notice about the usage of cookies and a selection of what cookies I want to have.

#### Note:
Inspecting my browser storage reveals that the page does not seem to use any cookies. Still I would expect to see a notice for that fact, maybe even advertising how much we value privacy and transparency.

**Comment by Levino** [comment]
Cookie notices are simply annoying. We will not add anything until we use cookies.
