### ISSUE TITLE
Keyword optimization of page content

### ISSUE THREAD

**Issue by jakobkolb** [hardforkio/homepage#419]
There is [a number of things that one can do](https://backlinko.com/seo-checklist) to be found on e.g. google for certain keywords.

First: 

- [ ] identify the keywords that we want to be found by

Then: 

- [ ] use keywords in urls
- [ ] use keywords in image alt description
- [ ] use keywords in site title and site meta description.

**Comment by Levino** [comment]
We do not optimize for google search so no need to waste money on seo optimization. As long as the checkers say our SEO is good, all is good with me.
