### ISSUE TITLE
Add internationalisation

### ISSUE THREAD

**Issue by kiliw** [hardforkio/homepage#61]
Related to #93.
Needs to be discussed how to do.

**Comment by Levino** [comment]
@manuelbieh Would you like to share some thoughts on this?

**Comment by manuelbieh** [comment]
I have used static json files and react-i18next for i18n. I'm not using Netlify (yet). I've googled a bit and I found gatsby-starter projects for i18n and for Netlify CMS but not for both at the same time. Looks like you can do some pioneering here 😉

**Comment by Levino** [comment]
Superseded by #141
