### ISSUE TITLE
Enable team section

### ISSUE THREAD

**Issue by kiliw** [hardforkio/homepage#91]
We want to be able to add team members via the CMS. Once a first team member has been added we want to show a team member section on the main landingpage (right before the contact component).

A team member needs the following data:
- Full name
- Job Title (localized)
- Degree (localized)
- Photo
- Social media (github or linkedin)

Q&A:
 - Create a new entry in the team members collection via the cms admin dashboard
 - Verify that the team section shows correctly in the preview for both languages en, de
 - Once published verify that the team section still is shown correctly.

**Comment by kiliw** [comment]
@Levino Do you have something special in mind for the team section or should we stick close to the one in the description?

**Comment by EmCeeEs** [comment]
Notes:
- Team members are added to the team members collection and referenced in the home collection.
- The component is not (yet) rendered correctly in the preview.
